FORMAT: 1A9
HOST: https://paper-scroll.ru/api/

# paper-scroll

Здесь представлен список доступных секций и методов API игры [Paper Scroll](https://vk.com/app7420483).

Любые вопросы вы можете задать в нашем [сообществе ВКонтакте](https://vk.com/paper_scroll) или [специальной беседе](https://vk.me/join/AJQ1d4PhyRd9VqY5MOofYEWD).

Для работы с API вам необходимо создать магазин внутри приложения и получить к нему ключ доступа по ссылке [vk.com/app7420483#create_merchant](https://vk.com/app7420483#create_merchant)

# Merchants [/merchants]

## merchants.get [GET /merchants.get]
    Возвращает информацию о магазинах по их идентификаторам 

+ Request (application/json)

    + Attributes

        + merchant_ids (array[number], optional) 
            ID магазинов, перечисленные через запятую. <br/>
            По умолчанию — идентификатор текущего магазина. <br/>
            Не больше 100 элементов.
        
    + Body

            {
                "merchant_ids": [1]
            }
            
+ Response 200 (application/json)
    + Attributes (object)
        + response (array[Merchant]) - Список магазинов
    

# Users [/users]

# Transfers [/transfers]

# Data Structures

## Merchant (object)
+ merchant_id: `1`, `2`, `3` (number) - ID магазина
+ owner_id: 595626484 (number) - ID владельца магазина
+ name: `Мой магазин` (string) - Название магазина
+ balance: 250000 (number) - Баланс магазина в тыс. долях рулонов
+ create_date: 1590134400 (number) - Дата создания магазина

## User (object)
+ user_id: 595626484 (number) - ID пользователя
+ first_name, last_name: `Pi Emerollo` (string) - Имя и Фамилия пользователя
+ avatar, avatar_max: `https://pp.userapi.com/...` - Фотографии из профиля пользователя
+ balance: 100000 (number) - Баланс пользователя в тыс. долях рулонов

## Transfer (object)
+ transfer_id: 37356 (number) - ID перевода
+ user_id: 595626484 (number) - ID инициатора перевода
+ peer_id: 100772411 (number) - ID получателя перевода
+ external_id: 37357 (number) - ID перевода для получателя
+ is_initiator: true (boolean) - Является ли текущий пользователь инициатором

+ type (enum[string])
    Тип перевода

    + Default: `transfer`
    + Members
        + `transfer` - Стандартный перевод
        + `merchant` - Перевод для магазина
        + `steal` - Кража другим пользователем (user-only)
        + `loss` - Потеря от заражения (user-only)
        + `achievement` - Бонус за полученное достижение (user-only)

+ object_type (enum[string])
    Тип переводимых предметов

    + Default: `balance`
    + Members
        + `balance` - Рулоны
        + `disinfectants` - Средства защиты
        + `items` - Предметы из инвентаря

+ object_type_id: 1 (number) 
    ID предмета при **object_type** = **disinfectants** или  **items**

+ amount: 1000 (number) 

    Переводимая сумма при **object_type** = **balance** <br/>
    В остальных случаях - количество переводимых предметов