FORMAT: 1A9
HOST: https://paper-scroll.ru/api/

# paper-scroll

Здесь представлен список доступных секций и методов API игры [Paper Scroll](https://vk.com/app7420483).

Любые вопросы о работе API вы можете задать в нашем [сообществе ВКонтакте](https://vk.com/paper_scroll) или [специальной беседе](https://vk.me/join/AJQ1d4PhyRd9VqY5MOofYEWD).

Для отправки запросов вам необходимо создать магазин внутри приложения и получить к нему ключ доступа по ссылке [vk.com/app7420483#create_merchant](https://vk.com/app7420483#create_merchant)

### Limitations

С использованием одного ключа доступа можно отправить не больше 3 запросов в секунду. 

Также с одного IP адреса в секунду можно отправить не больше 10 запросов в секунду.

### Errors handling

Ошибки API всегда возвращаются с HTTP кодом 400 Bad Request и имеют общий формат:

```
{
    "error": {
        "error_code": 1,
        "error_msg": "Internal error",
        "error_text": "Внутренняя ошибка сервиса, повторите запрос позже"
    }
}
```

Основной список ошибок, возвращаемых для всех методов:

- **#1 - Internal error** (Внутренняя ошибка сервиса)
- **#2 - Authorize error** (Неверно передан ключ доступа)
- **#3 - Access error** (Ошибка доступа к секции/методу)
- **#4 - Flood limit** (Превышен лимит на частоту обращений)
- **#5 - Unknown method** (Не определена секция/метод API)

Также в ходе выполнения могут произойти специальные ошибки, уникальные для каждого метода.

# Merchants [/merchants]

## merchants.get [GET /merchants.get] - Возвращает информацию о магазинах по их идентификаторам 

+ Request (application/json)
    + Attributes

        + merchant_ids (array[number], optional) 
            ID магазинов, перечисленные через запятую. <br/>
            По умолчанию — идентификатор текущего магазина. <br/>
            Не больше 100 элементов.
        
    + Body

            {
                "merchant_ids": [1]
            }
            
+ Response 200 (application/json)
    + Attributes (object)
        + response (array[Merchant]) - Список магазинов
        
+ Response 400 (application/json)
    + Attributes (Error)

# Users [/users]

# Transfers [/transfers]

# Data Structures

## User (object)
+ user_id: 595626484 (number) - ID пользователя
+ first_name, last_name: `Pi Emerollo` (string) - Имя и Фамилия пользователя
+ avatar, avatar_max: `https://pp.userapi.com/...` - Фотографии из профиля пользователя
+ balance: 100000 (number) - Баланс пользователя в тыс. долях рулонов

## Merchant (object)
+ merchant_id: `1`, `2`, `3` (number) - ID магазина
+ owner_id: 595626484 (number) - ID владельца магазина
+ name: `Мой магазин` (string) - Название магазина
+ balance: 250000 (number) - Баланс магазина в тыс. долях рулонов
+ create_date: 1590134400 (number) - Дата создания магазина

## Transfer (object)
+ transfer_id: 37356 (number) - ID перевода
+ user_id: 595626484 (number) - ID инициатора перевода
+ peer_id: 100772411 (number) - ID получателя перевода
+ external_id: 37357 (number) - ID перевода для получателя
+ is_initiator: true (boolean) - Является ли текущий пользователь инициатором

+ type (enum[string])
    Тип перевода

    + Default: `transfer`
    + Members
        + `transfer` - Стандартный перевод
        + `merchant` - Перевод для магазина
        + `steal` - Кража другим пользователем (user-only)
        + `loss` - Потеря от заражения (user-only)
        + `achievement` - Бонус за полученное достижение (user-only)

+ object_type (enum[string])
    Тип переводимых предметов

    + Default: `balance`
    + Members
        + `balance` - Рулоны
        + `disinfectants` - Средства защиты
        + `items` - Предметы из инвентаря

+ object_type_id: 1 (number) 
    При **object_type** = **disinfectants** или **items** содержит ID предмета <br/>
    При **object_type** = **balance** всегда имеет значение `0`

+ amount: 1000 (number) 

    Переводимая сумма при **object_type** = **balance** <br/>
    В остальных случаях - количество переводимых предметов
    
## Error (object)
+ error_code: 1 (required, string)
+ error_msg: `Example error` (required, string)
+ error_text: `Error message example` (required, string)